services:
  database:
    image: postgres:16
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticketing-app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ backend ]

  gateway-service:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        MODULE: gateway-service
    image: gateway-service:dev
    ports:
      - "8762:8762"
    depends_on:
      - discovery-service
      - user-service
      - project-service
      - task-service
    networks:
      - backend

  discovery-service:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        MODULE: discovery-service
    image: discovery-service:dev
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks: [ backend ]

  user-service:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        MODULE: user-service
    image: user-service:dev
    ports:
      - "9090:9090"
    depends_on:
      database:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9090/actuator/health || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks: [ backend ]

  project-service:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        MODULE: project-service
    image: project-service:dev
    ports:
      - "9091:9091"
    depends_on:
      database:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9091/actuator/health || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks: [ backend ]

  task-service:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        MODULE: task-service
    image: task-service:dev
    ports:
      - "9092:9092"
    depends_on:
      database:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9092/actuator/health || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks: [ backend ]

networks:
  backend:
    driver: bridge
